name: build

on:
  schedule:
      - cron: '0 22 * * *'
  push:
    branches: 
      - '*' 
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create sample script
        run: |
          #mkdir -p .debpkg/usr/bin
          #mkdir -p .debpkg/usr/lib/samplescript
          #echo -e "echo sample" > .debpkg/usr/bin/samplescript
          #chmod +x .debpkg/usr/bin/samplescript
          #echo -e "a=1" > .debpkg/usr/lib/samplescript/samplescript.conf
          app_name="fldigi"
          app_version="4.1.20"
          app_arch="arm64"
          mkdir $app_name'_'$app_version'_'$app_arch
          mkdir -p $app_name'_'$app_version'_'$app_arch/usr/local/bin
          cp ~/YourProjects/Hello/hello $app_name'_'$app_version'_'$app_arch/usr/local/bin
          mkdir $app_name'_'$app_version'_'$app_arch/DEBIAN
          touch $app_name'_'$app_version'_'$app_arch/DEBIAN/control
          
      - uses: jiro4989/build-deb-action@v2
        with:
          package: fldigi
          package_root: $app_name'_'$app_version'_'$app_arch
          maintainer: Maksym Shaposhnikov
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'libc6 (>= 2.29), libfltk-images1.3, libfltk1.3 (>= 1.3.4), libgcc-s1 (>= 4.0), libhamlib2, libpng16-16 (>= 1.6.2-1), libportaudio2 (>= 19+svn20101113), libpulse0 (>= 0.99.1), libsamplerate0 (>= 0.1.7), libsndfile1 (>= 1.0.20), libstdc++6 (>= 9), libudev1 (>= 183), libx11-6'
          desc: 'Fldigi'
